libxl: Fix duplicate libxl_ctx typedef.
commit de18e4c038306aeeca53e6e63e563036cafef162 introduces a build error with
older gcc:

In file included from xl.c:31:
libxl.h:582: error: redefinition of typedef ‘libxl_ctx’
libxl.h:348: note: previous declaration of ‘libxl_ctx’ was here

Signed-off-by: Wen Congyang <wency@cn.fujitsu.com>
Acked-by: Ian Campbell <ian.campbell@citrix.com>
[ ijc -- rewrote commit message ]