kexec: fix ia64 build for 21300:8bdf09baff30
On ia64, 21300:8bdf09baff30 introduces the following error:
  xen/common/kexec.c:490: undefined reference to
  `continue_hypercall_on_cpu'

The function continue_hypercall_on_cpu() is defined only on x86.

Signed-off-by: KUWAMURA Shin'ya <kuwa@jp.fujitsu.com>