arm: Fix build following c/s 8e2aa76dc
The ARM side of the cpu_nr_siblings() was missing a return type.  OSSTest
reports:

  /home/osstest/build.150502.build-arm64-xsm/xen/xen/include/asm/cpufeature.h:67:15:
  error: return type defaults to 'int' [-Werror=implicit-int]
   static inline cpu_nr_siblings(unsigned int)
                 ^~~~~~~~~~~~~~~

My local build test then reported:

  /local/xen.git/xen/include/asm/cpufeature.h: In function ‘cpu_nr_siblings’:
  /local/xen.git/xen/include/asm/cpufeature.h:67:1: error: parameter name omitted
   static inline int cpu_nr_siblings(unsigned int)
    ^

Fix it up to match its x86 counterpart.

Signed-off-by: Andrew Cooper <andrew.cooper3@citrix.com>