arm/optee: Fix arm32 build
A Travis randconfig build notices:

optee.c: In function ‘allocate_and_pin_shm_rpc’:
optee.c:383:13: error: format ‘%lx’ expects argument of type
   ‘long unsigned int’, but argument 5 has type ‘uint64_t’ [-Werror=format=]
    gdprintk(XENLOG_WARNING, "Guest tries to use the same RPC SHM cookie %lx\n",
             ^

Use PRIx64 instead of %lx

Full logs https://travis-ci.org/andyhhp/xen/jobs/551754253

Signed-off-by: Andrew Cooper <andrew.cooper3@citrix.com>
Reviewed-by: Stefano Stabellini <sstabellini@kernel.org>