xen: fix build when 'perfc=y'
Which was failing with this:

 viridian.c: In function ‘wrmsr_viridian_regs’:
 viridian.c:254:1: error: ‘PERFC_mshv_wrmsr_apic_msr’ undeclared
 (first use in this function)
 viridian.c:254:1: note: each undeclared identifier is reported only
 once for each function it appears in
 viridian.c: In function ‘rdmsr_viridian_regs’:
 viridian.c:305:1: error: ‘PERFC_mshv_rdmsr_apic_msr’ undeclared
 (first use in this function)

as a consequence of 17b754cab7b0 using but not defining
the counters.

Signed-off-by: Dario Faggioli <dario.faggioli@citrix.com>
Acked-by: George Dunlap <george.dunlap@eu.citrix.com>
Committed-by: Keir Fraser <keir@xen.org>
xen-unstable changeset: 26098:6d54c3338c52
xen-unstable date: Tue Oct 23 11:12:22 UTC 2012