fuzz: wrappers.c depends on x86_emulate.h
In my automated SLE_11 builds I often see failures like that:

[   74s] wrappers.c:5:25: error: x86-emulate.h: No such file or directory
[   74s] make[6]: *** [wrappers.o] Error 1

Signed-off-by: Olaf Hering <olaf@aepfle.de>

Move line to where it belongs.

Signed-off-by: Jan Beulich <jbeulich@suse.com>