tools/libxl: libxl_set_memory_target: Fix compile error in backport
013ee593ca04 the backport of "libxl: fix libxl_set_memory_target"
was broken:

  libxl.c:5034:5: error: 'r' undeclared (first use in this function)

This is because this old version of the function uses
(inappropriately) rc for libxc error returns.

Fix this by introducing `int r'.  We now use this in our backport,
even though the rest of the function is incoherent about the use of
rc.

Reported-by: Doug Goldstein <cardoe@cardoe.com>
Signed-off-by: Ian Jackson <Ian.Jackson@eu.citrix.com>