[IA64] fix missing header: asm/fpswa.h
This patch fixes the following error in recent kernel:
  ia64/asm/dom_fw_common.h:47:23: error: asm/fpswa.h: No such file or
  directory

Signed-off-by: KUWAMURA Shin'ya <kuwa@jp.fujitsu.com>
xen-unstable changeset:   22941:d12a28ef91b9
xen-unstable date:        Fri Feb 18 10:21:19 2011 +0000