xen/credit2: Fix build following c/s 8e2aa76dc (take 2)
OSSTest reports:

  credit2.c: In function 'cpu_runqueue_siblings_match':
  credit2.c:883:29: error: implicit declaration of function 'cpu_nr_siblings' [-Werror=implicit-function-declaration]
       unsigned int nr_sibls = cpu_nr_siblings(cpu);
                               ^~~~~~~~~~~~~~~
  credit2.c:883:5: error: nested extern declaration of 'cpu_nr_siblings' [-Werror=nested-externs]
       unsigned int nr_sibls = cpu_nr_siblings(cpu);
       ^~~~~~~~
  cc1: all warnings being treated as errors

For whatever reason, cpufeature.h's inclusion is conditional, and missing for
arm32.  Inlcude it explicitly.

Signed-off-by: Andrew Cooper <andrew.cooper3@citrix.com>