vMSI: fix ia64 build for 21577:c41ab909f08e
On ia64, 21577:c41ab909f08e introduces the following error:
  /xen/include/xen/pci.h:52: warning: implicit declaration of function
  `PFN_UP'
  /xen/include/xen/pci.h:52: error: variable-size type declared
  outside of any function
  /xen/include/xen/pci.h:53: error: variable-size type declared
  outside of any function

Because the macro PFN_UP() is defined on x86 only.

Signed-off-by: Keir Fraser <keir@xen.org>
Signed-off-by: KUWAMURA Shin'ya <kuwa@jp.fujitsu.com>
xen-unstable changeset:   23074:c80e0fb4fe93
xen-unstable date:        Wed Mar 23 13:34:55 2011 +0000