libxl: Revert 3658f7a0bdd8 "libxl: fix libxl_set_memory_target"
I backported
  3658f7a0bdd8fcda217559927e25263a07398c27
  libxl: fix libxl_set_memory_target
but this was not necessary, because the commit it fixes is not in
Xen 4.6.

So the backport introduces a duplicate cal to xc_domain_getinfolist
and also breaks the build with
    libxl.c:4908:5: error: ‘r’ undeclared (first use in this function)

Signed-off-by: Ian Jackson <ian.jackson@eu.citrix.com>