x86/mm: initialize ol1e in create_grant_pv_mapping() for older compilers
On gcc 4.4.4:

mm.c: In function create_grant_pv_mapping:
mm.c:3839: error: ol1e.l1 may be used uninitialized in this function

While ol1e would not be used uninitialized (because rc needs to be properly
set) we have to accommodate these older compliers.

Signed-off-by: Boris Ostrovsky <boris.ostrovsky@oracle.com>
Reviewed-by: Jan Beulich <jbeulich@suse.com>